services:
  - type: web
    name: stylesense-api
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: IBM_API_KEY
        sync: false
      - key: IBM_PROJECT_ID
        sync: false
      - key: HF_API_KEY
        sync: false
